version: 0.1.0
name: tsproject
description: description
tagNames:
  - default-tag-from-loc-cli
timeoutSeconds: 180
aggregatorLogic:
  name: aggregator
  file: aggregator-logic.ts
genericLogics:
  - name: generic-1
    file: 1.ts
    tagNames:
      - default-tag-from-loc-cli
  - name: generic-2
    file: 2.ts
    tagNames:
      - default-tag-from-loc-cli
